# Pre-commit hooks for code quality
# Install: pip install pre-commit && pre-commit install

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    exclude: ^(algorithms_impl/|DiskANN/)
  - id: end-of-file-fixer
    exclude: ^(algorithms_impl/|DiskANN/)
  - id: check-yaml
  - id: check-json
  - id: check-merge-conflict

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black
    exclude: ^(algorithms_impl/|DiskANN/|venv/|env/)

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
  - id: flake8
    args: ['--max-line-length=127']
    exclude: ^(algorithms_impl/|DiskANN/|venv/|env/)
