pipeline:
  name: "sage-api-operator-operator_test"
  description: "Test pipeline for Sage API Operator"
  version: "1.0.0"
  type: "ray"

source:
  data_path: "./sage/api/operator/operator_test/question.txt"

chunk:
  chunk_size: 512
  overlap: 128

writer:
  stm: False
  ltm: True
  dcm: False

sink:
  file_path: mem_output.txt

