name: llh
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=py311h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.4=hbda6634_3
  - faiss-gpu=1.9.0=py3.11_ha2e4562_0_cuda12.1.1
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=h99ab3db_1
  - libcurand=10.3.5.147=h99ab3db_1
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libfaiss=1.9.0=h4818125_0_cuda12.1.1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.10=py311h5eee18b_0
  - mkl_random=1.2.7=py311ha02d727_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py311h06a4308_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=24.1=py311h06a4308_0
  - pillow=10.4.0=py311h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - pluggy=1.0.0=py311h06a4308_1
  - pysocks=1.7.1=py311h06a4308_0
  - pytest=7.4.4=py311h06a4308_0
  - python=3.11.10=he870216_0
  - pytorch=2.4.0=py3.11_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_0
  - setuptools=75.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.4.0=py311_cu121
  - torchtriton=3.0.0=py311
  - typing_extensions=4.11.0=py311h06a4308_0
  - urllib3=2.2.3=py311h06a4308_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.9
      - aiosignal==1.3.1
      - airportsdata==20241001
      - annotated-types==0.7.0
      - anyio==4.6.0
      - appdirs==1.4.4
      - attrs==24.2.0
      - backoff==2.2.1
      - bitsandbytes==0.44.1
      - boilerpy3==1.0.7
      - cattrs==24.1.2
      - click==8.1.7
      - cloudpickle==3.1.0
      - cmake==3.30.4
      - compressed-tensors==0.6.0
      - construct==2.5.3
      - datasets==3.0.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - docopt==0.6.2
      - einops==0.8.0
      - environs==9.5.0
      - evaluate==0.4.3
      - events==0.5
      - fastapi==0.115.2
      - filelock==3.16.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gguf==0.10.0
      - greenlet==3.1.1
      - grpcio==1.67.0
      - h11==0.14.0
      - haystack-ai==2.6.1
      - haystack-experimental==0.2.0
      - httpcore==1.0.6
      - httptools==0.6.4
      - httpx==0.27.2
      - huggingface-hub==0.25.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - inflect==7.4.0
      - interegular==0.3.3
      - jieba==0.42.1
      - jiter==0.6.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - lark==1.2.2
      - lazy-imports==0.3.1
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.6
      - loguru==0.7.2
      - markupsafe==3.0.1
      - marshmallow==3.23.0
      - milvus-haystack==0.0.11
      - milvus-lite==2.4.10
      - mistral-common==1.4.4
      - monotonic==1.6
      - more-itertools==10.5.0
      - msgpack==1.1.0
      - msgspec==0.18.6
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - ninja==1.11.1.1
      - nltk==3.9.1
      - num2words==0.5.13
      - numba==0.60.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.51.2
      - opencv-python-headless==4.10.0.84
      - outlines==0.0.46
      - outlines-core==0.1.14
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post4
      - pefile==2024.8.26
      - platformdirs==4.3.6
      - posthog==3.7.0
      - prometheus-client==0.21.0
      - prometheus-fastapi-instrumentator==7.0.0
      - prompthub-py==4.0.0
      - propcache==0.2.0
      - protobuf==5.28.2
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pyarrow==17.0.0
      - pycountry==24.6.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pymilvus==2.4.8
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-ptrace==0.9.9
      - pytz==2024.2
      - pyzmq==26.2.0
      - quantulum3==0.9.2
      - rank-bm25==0.2.2
      - ray==2.37.0
      - referencing==0.35.1
      - regex==2024.9.11
      - requests-cache==0.9.8
      - rouge-score==0.1.2
      - rpds-py==0.20.0
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sentence-transformers==3.1.1
      - sentencepiece==0.2.0
      - six==1.16.0
      - sniffio==1.3.1
      - sqlalchemy==1.3.24
      - sseclient-py==1.8.0
      - starlette==0.40.0
      - tenacity==9.0.0
      - text2vec==1.3.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.20.1
      - torchvision==0.19.0
      - tqdm==4.66.5
      - transformers==4.45.2
      - triton==2.3.0
      - typeguard==4.3.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - ujson==5.10.0
      - url-normalize==1.4.3
      - uvicorn==0.32.0
      - uvloop==0.21.0
      - vllm==0.6.3.post1
      - watchfiles==0.24.0
      - websockets==13.1
      - xformers==0.0.27.post2
      - xxhash==3.5.0
      - yarl==1.14.0
      - zipp==3.20.2
prefix: /miniconda3/envs/llh
